### ISSUE TITLE
Fix old urls in posts

### ISSUE THREAD

**Issue by dingeins** [ODataOrg/odataorg.github.io#19]
Some of them are `www.odata.org/blog/yyyy/mm/dd/title`, some of them are not valid anymore. Need fixing.

**Comment by dingeins** [comment]
Another example would be `www.odata.org/mailing-list`

**Comment by liqian19891011** [comment]
Checked all posts, URL are correct.
As for changing www.odata.org/mailing-list, the URL has been broken for quite a while and referred in old posts, hold the fix.
