### ISSUE TITLE
Invalid json indentation and inconsistencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ODataOrg/odataorg.github.io#57]
Misindented json right on the homepage:
![image](https://cloud.githubusercontent.com/assets/159209/8164923/30b4ee50-1341-11e5-8090-678e919799dc.png)

Space inconsistencies just below that:
![image](https://cloud.githubusercontent.com/assets/159209/8164917/299d2b96-1341-11e5-82f4-818194a93de3.png)

**Comment by MikeyBurkman** [comment]
This is still very much broken on the OData in 6 steps page, on each example HTTP request. http://www.odata.org/getting-started/understand-odata-in-6-steps/

Also, it's not technically valid JSON. JSON uses double quotes, not single quotes.

**Comment by chinadragon0515** [comment]
@MikeyBurkman First closed issue are not been monitored, I will suggest you open new issues if there is some issues, and you can add reference to some existing closed issues.

Second, in the code library, we support both double and single quotes. 

Third, I open issue to change to double quotes, we are welcome contribution on this.
