### ISSUE TITLE
don't auto-convert double-quotes into single-quotes in your js/json/node docs

### ISSUE THREAD

**Issue by dym-cx** [ODataOrg/odataorg.github.io#61]
promotes `'russellwhyte'` to a syntax error:
![screen shot 2015-06-30 at 12 38 01 pm](https://cloud.githubusercontent.com/assets/9968388/8429153/42571e0e-1f25-11e5-94cb-7e874b1d62f9.png) ![screen shot 2015-06-30 at 12 38 14 pm](https://cloud.githubusercontent.com/assets/9968388/8429154/427e48b2-1f25-11e5-8477-d8538a64a842.png)

same with json-responses:
![screen shot 2015-06-30 at 12 42 07 pm](https://cloud.githubusercontent.com/assets/9968388/8429181/85583ed6-1f25-11e5-8e39-37221e39e23e.png)

**Comment by dingeins** [comment]
Fixed. See the latest 3 commits. For JS code I chose the single quote favored syntax. But all the instances like `'People('russellwhyte')'` is corrected as `'People("russellwhyte")'`.
