### ISSUE TITLE
Return value of indexof needs clearification

### ISSUE THREAD

**Issue by esditm** [ODataOrg/odataorg.github.io#63]
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398121

> 5.1.1.4.5 indexof
> 
> The indexof function has the following signature:
> Edm.Int32 indexof(Edm.String,Edm.String)
> 
> The indexof function returns the zero-based character position of the first occurrence of the second parameter value in the first parameter value. The indexOfMethodCallExpr syntax rule defines how the indexof function is invoked.
> Example 59: all customers with a CompanyName containing 'lfreds' starting at the second character
>
> http://host/service/Customers?$filter=indexof(CompanyName,'lfreds') eq 1

No mention of what value should be returned when there's no match. `-1` or `null` are both valid assumptions.
It needs to specified to avoid incorrect implementations :)

One could argue that the return type is `Edm.Int32` and therefore it should be `-1`. But I'm not sure if the Edm types are nullable.

In any case https://github.com/OData/WebApi uses `null`.

**Comment by dingeins** [comment]
@esditm This is a very good suggestion. The protocol does lack such specification. We'd recommend you report this to https://issues.oasis-open.org/browse/ODATA/ so that the TC can keep track of it and add it to the next errata.

**Comment by esditm** [comment]
I can't create a user on the OASIS site. So I can't create an issue for this.
Anyone with an account that want to do it?

**Comment by ralfhandl** [comment]
This is already covered by https://issues.oasis-open.org/browse/ODATA-780
We opted for `-1`

**Comment by esditm** [comment]
Fantastic! :+1:

**Comment by ralfhandl** [comment]
You can provide feedback on the OData specification via the odata-comment mailing list, see instructions on https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=odata
